# Select image from https://hub.docker.com/_/php/
image: php:7.1

# Select what we should cache
cache:
  paths:
  - vendor/

before_script:
# Install git, the php image doesn't have installed
- apt-get update -yqq
- apt-get install git -yqq
- apt-get install libpq-devel -yqq

# Install mysql driver
- docker-php-ext-install pdo_mysql
- docker-php-ext-install pdo_pgsql

# Install composer
- curl -sS https://getcomposer.org/installer | php

# Install all project dependencies
- php composer.phar install

services:
- mysql
- postgres

variables:
  # Configure mysql service (https://hub.docker.com/_/mysql/)
  MYSQL_DATABASE: hello_world_test
  MYSQL_ROOT_PASSWORD: mysql
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: hello_world_test

# We test PHP7 with MySQL, but we allow it to fail
test:php7:mysql:
  image: php:7.1
  script:
  - vendor/bin/phpunit --configuration phpunit_mysql.xml --coverage-text
  - vendor/bin/phpunit --configuration phpunit_pgsql.xml --coverage-text
  allow_failure: true
