version: "3"
services:
  my_app:
    build: .
    container_name: app_container_dev
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html:rw
    depends_on:
      - app_db_dev
    links:
      - app_db_dev
  app_db_dev:
    image: postgres:10.1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hello_world_test
    ports:
      - "5432:5432"
